version: '3.7'
services:
  mysql:
    build: ./base-datos
    #en teoria con este comando se vuelve al metodo de autenticacion de mysql 5
    command: --default-authentication-plugin=mysql_native_password 
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: "pass123"
      MYSQL_ALLOW_EMPTY_PASSWORD: "true"
      MSYQL_USER: "profesor"
      MYSQL_PASSWORD: "pass123"
    healthcheck:
      test: "exit 0"
    ports:
      - "3306:3306"

  chaeaparser:
    build: .
    depends_on:
      - mysql
    # command: ["./wait-for-it.sh", "mysql:3306", "--", "node", "server.js" ]
    ports:
      - "3002:3002"
    environment:
      WAIT_HOSTS: mysql:3306
